# Generated by Django 5.2.5 on 2025-12-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_amts", "0005_remove_ticket_passenger_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activebus",
            name="is_accident",
            field=models.BooleanField(default=False, help_text="Accident detected"),
        ),
        migrations.AddField(
            model_name="activebus",
            name="is_manual_stop",
            field=models.BooleanField(
                default=False, help_text="Bus manually stopped by driver"
            ),
        ),
        migrations.AddField(
            model_name="activebus",
            name="last_movement_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="activebus",
            name="speed",
            field=models.FloatField(default=0.0, help_text="Current speed in km/h"),
        ),
    ]
