# Generated by Django 5.2.5 on 2025-12-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_amts", "0006_activebus_is_accident_activebus_is_manual_stop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activebus",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activebus",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activebus",
            name="is_accident",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activebus",
            name="is_manual_stop",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activebus",
            name="speed",
            field=models.FloatField(default=45.0),
        ),
    ]
