# Generated by Django 5.2.5 on 2025-12-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_amts", "0007_activebus_latitude_activebus_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activebus",
            name="last_movement_time",
        ),
        migrations.AlterField(
            model_name="activebus",
            name="is_accident",
            field=models.BooleanField(
                default=False, help_text="True if accident/breakdown detected"
            ),
        ),
        migrations.AlterField(
            model_name="activebus",
            name="is_manual_stop",
            field=models.BooleanField(
                default=False, help_text="True if driver manually stopped bus"
            ),
        ),
        migrations.AlterField(
            model_name="activebus",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Current latitude position", null=True
            ),
        ),
        migrations.AlterField(
            model_name="activebus",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Current longitude position", null=True
            ),
        ),
        migrations.AlterField(
            model_name="activebus",
            name="speed",
            field=models.FloatField(default=45.0, help_text="Current speed in km/h"),
        ),
    ]
