# Generated by Django 5.2.5 on 2025-12-25 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_amts", "0008_remove_activebus_last_movement_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activebus",
            name="speed",
            field=models.FloatField(default=35.0, help_text="Current speed in km/h"),
        ),
        migrations.CreateModel(
            name="BusPass",
            fields=[
                (
                    "pass_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly Pass"),
                            ("STUDENT", "Student Pass"),
                        ],
                        max_length=10,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("from_stop", models.CharField(max_length=100)),
                ("to_stop", models.CharField(max_length=100)),
                ("route_number", models.CharField(max_length=10)),
                (
                    "school_college_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("student_id", models.CharField(blank=True, max_length=50, null=True)),
                ("class_year", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="pass_photos/"),
                ),
                (
                    "id_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="pass_documents/"
                    ),
                ),
                (
                    "student_id_card",
                    models.FileField(
                        blank=True, null=True, upload_to="pass_documents/"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="pass_pdfs/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Pass",
                "verbose_name_plural": "Bus Passes",
                "ordering": ["-application_date"],
            },
        ),
    ]
